In [1]:
# AI Investment Opportunity Analyzer
# Notebook 06: Final Pipeline Test

import pandas as pd
import sys
from pathlib import Path

# Project paths
PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw"

# Add src folder to Python path
sys.path.append(str(SRC_PATH))

from predict import predict_investment_opportunity

# Load raw dataset
df = pd.read_csv(RAW_DATA_PATH / "synthetic_investment_opportunities.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (5000, 42)

,opportunity_id,opportunity_name,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,...,social_impact_score,governance_score,sustainability_score,risk_adjusted_roi,profitability_index,payback_efficiency,market_attractiveness_score,financial_strength_score,investment_score,recommendation
0,INV-00001,Tabuk Technology Opportunity,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,...,53.23,83.81,77.54,0.2860,0.2266,1.1252,58.80,40.56,80.10,Invest
1,INV-00002,Asir Healthcare Opportunity,Healthcare,Asir,Medium,67.46,47.73,11.44,19.08,20.73,...,65.18,64.37,73.71,0.5777,0.7165,3.0874,49.96,62.20,90.23,Invest
2,INV-00003,Eastern Province Education Opportunity,Education,Eastern Province,High,213.29,165.94,12.03,8.38,7.92,...,18.88,54.31,52.59,0.1871,0.0943,1.0897,70.11,36.20,22.60,Reject
3,INV-00004,Madinah Logistics Opportunity,Logistics,Madinah,Medium,23.72,19.82,3.41,16.41,18.17,...,54.31,70.71,48.25,0.3275,1.0910,3.8163,55.75,52.93,76.81,Invest
4,INV-00005,Qassim Technology Opportunity,Technology,Qassim,High,131.04,84.34,21.33,9.21,9.21,...,54.64,63.07,72.57,0.1696,0.5224,1.3329,52.97,38.86,32.86,Reject

In [2]:
# Prepare one sample opportunity for prediction

drop_columns = [
    "opportunity_id",
    "opportunity_name",
    "investment_score",
    "recommendation"
]

sample_input = df.drop(columns=drop_columns).iloc[[0]]

sample_input

,sector,region,competition_level,investment_size_million,capex_million,opex_million,expected_roi_percent,irr_percent,payback_period_years,revenue_growth_percent,...,strategic_impact_score,environmental_impact_score,social_impact_score,governance_score,sustainability_score,risk_adjusted_roi,profitability_index,payback_efficiency,market_attractiveness_score,financial_strength_score
0,Technology,Tabuk,Low,163.15,91.34,22.63,14.29,17.19,11.7,6.75,...,81.17,95.59,53.23,83.81,77.54,0.286,0.2266,1.1252,58.8,40.56

In [3]:
# Predict investment score and recommendation

prediction_result = predict_investment_opportunity(sample_input)

prediction_result[
    [
        "predicted_investment_score",
        "recommendation"
    ]
]

   predicted_investment_score recommendation
0                        71.4         Review